# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

@typing.final
class PyAsyncIterator[T]:
    r"""
    Async iterator wrapper used by the native module.
    
    Notes
    -----
    This is an internal type and not meant to be constructed directly.
    """
    def __aiter__(self) -> PyAsyncIterator[T]:
        r"""
        Return self as an async iterator.
        
        Returns
        -------
        PyAsyncIterator[T]
        """
    def __anext__(self) -> typing.Coroutine[typing.Any, typing.Any, T]:
        r"""
        Await the next item from the iterator.
        
        Returns
        -------
        typing.Coroutine[typing.Any, typing.Any, T]
        """

