# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

@typing.final
class PyAsyncIterator[T]:
    def __aiter__(self) -> PyAsyncIterator[T]: ...
    def __anext__(self) -> typing.Coroutine[typing.Any, typing.Any, T]: ...
