# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import asyncio
import builtins
import enum
import typing

import pyarrow
from discord.ext.songbird.native.player import InputBase

@typing.final
class AudioInput(InputBase):
    def __new__(cls, array: pyarrow.Array, codec: SupportedCodec) -> typing.Self: ...

@typing.final
class RawPCMInput(InputBase):
    def __new__(
        cls, array: pyarrow.Float32Array, *, sample_rate: builtins.int = 48000, channels: builtins.int = 2
    ) -> typing.Self: ...

@typing.final
class StreamInput(InputBase):
    def __new__(cls, stream_reader: asyncio.StreamReader, codec: SupportedCodec) -> typing.Self: ...

@typing.final
class SupportedCodec(enum.Enum):
    MP3 = ...
    WAVE = ...
    MKV = ...
    FLAC = ...
    AAC = ...
