# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

class PyControlError(PySongbirdError): ...

class PyJoinError(PySongbirdError):
    r"""
    Raised when a voice join fails.
    """

    ...

class PyPlayerError(PySongbirdError): ...

class PySongbirdError:
    r"""
    Base exception for Songbird backend errors.
    """

    ...
