# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

class PyJoinError(builtins.PySongbirdError):
    ...

class PySongbirdError(builtins.Exception):
    ...

