# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

import discord

from . import error

class SongbirdImpl:
    r"""
    Internal backend for Songbird voice connections.

    This class is exposed to Python and used by `SongbirdClient` to manage
    voice state and connection lifecycle.
    """
    def __new__(cls, client: discord.Client, connectable: discord.abc.Connectable) -> SongbirdImpl:
        r"""
        Create a new backend tied to a Discord client and connectable.

        Parameters
        ----------
        client: discord.Client
            The Discord client instance.

        connectable: discord.abc.Connectable
            A connectable voice target (e.g., VoiceChannel or StageChannel).
        """
    def connect(
        self,
        *,
        timeout: builtins.float,
        reconnect: builtins.bool,
        self_deaf: builtins.bool = False,
        self_mute: builtins.bool = False,
    ) -> typing.Coroutine[typing.Any, typing.Any, None]:
        r"""
        |coro|

        Connect to the voice channel associated with this backend.

        Parameters
        ----------
        timeout: float
            Gateway connection timeout in seconds.
        reconnect: bool
            Whether to allow to reconnect attempts (currently ignored).
        self_deaf: bool
            Whether to deafen this account after connecting.
        self_mute: bool
            Whether to mute this account after connecting.

        Returns
        -------
        None
        """
    async def disconnect(self, *, force: builtins.bool) -> None:
        r"""
        |coro|

        Disconnect from the current voice channel.

        Parameters
        ----------
        force: bool
            Whether to force disconnect (currently ignored).

        Returns
        -------
        None
        """
    async def update_server(self, endpoint: builtins.str, token: builtins.str) -> None:
        r"""
        |coro|

        Update voice server information.

        This is typically invoked by discord.py during a voice handshake.

        Parameters
        ----------
        endpoint: str
            Voice server endpoint.
        token: str
            Voice session token.

        Returns
        -------
        None
        """
    async def update_state(self, session_id: builtins.str, channel_id: int | None = None) -> None:
        r"""
        |coro|

        Update voice state information.

        This is typically invoked by discord.py after a VOICE_STATE_UPDATE.

        Parameters
        ----------
        session_id: str
            Voice session ID.
        channel_id: int | None
            Channel ID, or None if disconnecting.

        Returns
        -------
        None
        """
    async def update_hook(
        self, channel_id: typing.Optional[builtins.int], self_mute: builtins.bool, self_deaf: builtins.bool
    ) -> None:
        r"""
        |coro|

        Hook invoked when discord.py updates voice state.

        Subclasses should override this to integrate with their event loop.

        Parameters
        ----------
        channel_id: int | None
            Channel ID, or None if disconnecting.
        self_mute: bool
            Whether the account is self-muted.
        self_deaf: bool
            Whether the account is self-deafened.

        Returns
        -------
        None
        """
    async def deafen(self, self_deaf: builtins.bool) -> None:
        r"""
        |coro|

        Deafen or undeafen this account.

        Parameters
        ----------
        self_deaf: bool
            Whether to deafen or undeafen this account.

        Returns
        -------
        None
        """
    async def mute(self, self_mute: builtins.bool) -> None:
        r"""
        |coro|

        Mute or unmute this account.

        Parameters
        ----------
        self_mute: bool
            Whether to mute or unmute this account.

        Returns
        -------
        None
        """
    def is_mute(self) -> builtins.bool:
        r"""
        Check if this account is muted.

        Returns
        -------
        bool
            Whether this account is muted.
        """
    def is_deaf(self) -> builtins.bool:
        r"""
        Check if this account is deafened.

        Returns
        -------
        bool
            Whether this account is deafened.
        """
    def move_to(self, channel: discord.abc.Snowflake) -> typing.Coroutine[typing.Any, typing.Any, None]:
        r"""
        |coro|

        Move this account to another voice channel.

        Parameters
        ----------
        channel: discord.abc.Snowflake | None
            The channel to move to.
            If None, disconnects from voice.
        """
