# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import asyncio
import builtins
import datetime
import enum
import typing

import pyarrow

@typing.final
class AudioInput(InputBase):
    r"""
    Encoded audio input backed by a pyarrow array.

    Notes
    -----
    The payload is interpreted according to `SupportedCodec`.
    """
    def __new__(cls, array: pyarrow.Array, codec: SupportedCodec) -> typing.Self:
        r"""
        Create an encoded audio input.

        Parameters
        ----------
        array : pyarrow.Array
            Encoded audio payload.
        codec : SupportedCodec
            Codec hint for decoding.

        Returns
        -------
        AudioInput
        """

class InputBase:
    r"""
    Base class for player inputs.

    Notes
    -----
    Concrete inputs are provided under `discord.ext.songbird.player.input`.
    """

    ...

@typing.final
class Queue:
    r"""
    Track queue controller.

    Notes
    -----
    Exposes queue operations for the active voice call.
    """
    def current(self) -> typing.Optional[TrackHandle]:
        r"""
        Return the currently playing track handle, if any.

        Returns
        -------
        TrackHandle | None
        """
    def dequeue(self, index: builtins.int) -> typing.Optional[TrackHandle]:
        r"""
        Remove and return a queued track handle by index.

        Parameters
        ----------
        index : int
            Zero-based index in the queue.

        Returns
        -------
        TrackHandle | None
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Check whether the queue is empty.

        Returns
        -------
        bool
        """
    def pause(self) -> None:
        r"""
        Pause all tracks in the queue.

        Returns
        -------
        None
        """
    def resume(self) -> None:
        r"""
        Resume all tracks in the queue.

        Returns
        -------
        None
        """
    def stop(self) -> None:
        r"""
        Stop playback and clear the queue.

        Returns
        -------
        None
        """
    def skip(self) -> None:
        r"""
        Skip the current track.

        Returns
        -------
        None
        """
    def tracks(self) -> builtins.list[TrackHandle]:
        r"""
        Return handles for all queued tracks.

        Returns
        -------
        list[TrackHandle]
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of queued tracks.

        Returns
        -------
        int
        """
    def __getitem__(self, item: builtins.int) -> typing.Optional[TrackHandle]:
        r"""
        Return a queued track handle by index.

        Parameters
        ----------
        item : int
            Zero-based index in the queue.

        Returns
        -------
        TrackHandle | None
        """

@typing.final
class RawPCMInput(InputBase):
    r"""
    Raw PCM input backed by a float32 array.

    Notes
    -----
    Samples are expected to be interleaved float32 PCM.
    """
    def __new__(
        cls, array: pyarrow.FloatArray, *, sample_rate: builtins.int = 48000, channels: builtins.int = 2
    ) -> typing.Self:
        r"""
        Create a raw PCM input.

        Parameters
        ----------
        array : pyarrow.Float32Array
            Interleaved PCM samples.
        sample_rate : int, optional
            Sample rate in Hz.
        channels : int, optional
            Channel count.

        Returns
        -------
        RawPCMInput
        """

@typing.final
class StreamInput(InputBase):
    r"""
    Stream input backed by an asyncio StreamReader.

    Notes
    -----
    This is intended for long-running or live audio sources.
    """
    def __new__(cls, stream_reader: asyncio.StreamReader, codec: SupportedCodec) -> typing.Self:
        r"""
        Create a stream input.

        Parameters
        ----------
        stream_reader : asyncio.StreamReader
            The source stream to read from.
        codec : SupportedCodec
            Codec hint for decoding.

        Returns
        -------
        StreamInput
        """

@typing.final
class Track:
    r"""
    Playable audio track.

    Notes
    -----
    Tracks are created from an `InputBase` and played via the voice client.

    Examples
    --------
    ```python
    track = player.Track(source)
    track = track.volume(0.8)
    ```
    """
    def __new__(cls, input: InputBase) -> Track:
        r"""
        Create a new track from an input source.

        Parameters
        ----------
        input : InputBase
            The audio input source.

        Returns
        -------
        Track
        """
    def play(self) -> Track:
        r"""
        Mark this track as playing.

        Returns
        -------
        Track
            This track.
        """
    def pause(self) -> Track:
        r"""
        Mark this track as paused.

        Returns
        -------
        Track
            This track.
        """
    def stop(self) -> Track:
        r"""
        Mark this track as stopped.

        Returns
        -------
        Track
            This track.
        """
    def volume(self, volume: builtins.float) -> Track:
        r"""
        Set the track volume multiplier.

        Parameters
        ----------
        volume : float
            Volume multiplier.

        Returns
        -------
        Track
            This track.
        """

@typing.final
class TrackHandle:
    r"""
    Handle for controlling a playing track.

    Notes
    -----
    Returned by `SongbirdImpl.play`.
    """
    def seek(self, position: datetime.timedelta) -> typing.Coroutine[typing.Any, typing.Any, datetime.timedelta]: ...
    def play(self) -> None:
        r"""
        Resume playback.

        Returns
        -------
        None
        """
    def pause(self) -> None:
        r"""
        Pause playback.

        Returns
        -------
        None
        """
    def stop(self) -> None:
        r"""
        Stop playback.

        Returns
        -------
        None
        """
    def enable_loop(self) -> None: ...
    def disable_loop(self) -> None: ...
    def loop_for(self, times: builtins.int) -> None: ...

@typing.final
class SupportedCodec(enum.Enum):
    r"""
    Codec hint for encoded audio inputs.

    Notes
    -----
    Used by `AudioInput` and `StreamInput` to describe the payload format.
    """

    MP3 = ...
    WAVE = ...
    MKV = ...
    FLAC = ...
    AAC = ...
