name: CI
on:
  push:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Check Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.13t"
          - "3.14"
          - "3.14t"
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopus-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: rustup component add clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Add problem matchers
        run: echo "::add-matcher::.github/rust.json"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "0.11.7"
          python-version: ${{ matrix.python-version }}

      - name: Syncing uv project
        run: uv sync --all-extras --dev --no-install-project --frozen --python ${{ matrix.python-version }}

      - name: Check Python ABI
        run: |
          if [[ "${{ matrix.python-version }}" == *t ]]; then
            uv run --no-sync python -c "import sys; assert not sys._is_gil_enabled()"
          else
            uv run --no-sync python -c "import sys; assert sys._is_gil_enabled()"
          fi

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: PYO3_PYTHON="$PWD/.venv/bin/python" cargo clippy --all-features --all-targets

      - name: Build wheels for checking
        run: PYO3_PYTHON="$PWD/.venv/bin/python" uv run --no-sync maturin develop

      - name: Run ruff
        run: uv run --no-sync ruff check --output-format=github

      - name: Run ruff formatter
        run: uv run --no-sync ruff format --diff

      - name: Run ty
        run: |
          ty_python_version="${{ matrix.python-version }}"
          ty_python_version="${ty_python_version%t}"
          uv run --no-sync ty check --output-format=github --python-version "$ty_python_version"
